import { Metadata } from 'next';
import '../styles/globals.css';
import '../styles/nes.css';
import '../styles/fonts.css';

export const runtime = 'edge';

export const metadata: Metadata = {
  title: 'Choose Your Own AIdventure - RPG Text Game',
  description:
    'Experience a unique RPG adventure generated by AI. Choose between Medieval and Sci-Fi settings and embark on a journey where your choices matter.',
  keywords: 'RPG, AI, Text Game, Adventure, Medieval, Sci-Fi, Interactive Fiction',
  openGraph: {
    type: 'website',
    url: 'https://chooseyourownadventure.vercel.app/',
    title: 'Choose Your Own AIdventure - AI RPG Game',
    description:
      'An old-school style of RPG created using AI. Get a new Adventure every time!',
    images: ['https://chooseyourownadventure.vercel.app/og-image.png'],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Choose Your Own AIdventure - AI RPG Game',
    description:
      'An old-school style of RPG created using AI. Get a new Adventure every time!',
    images: ['https://chooseyourownadventure.vercel.app/og-image.png'],
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
