import { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import React, { useEffect } from "react";
import { useKonami } from 'react-konami-code';
import Header from "./components/header"

export const runtime = 'experimental-edge';


const HomePage: NextPage = () => {

  useEffect(() => {
    // This useEffect is used for other purposes, not for handling the Konami code
  }, []);

  return (
    <>
      <Head>
        <title>Choose Your Own AIdventure - RPG Text Game</title>
        <meta name="description" content="Experience a unique RPG adventure generated by AI. Choose between Medieval and Sci-Fi settings and embark on a journey where your choices matter." />
        <meta name="keywords" content="RPG, AI, Text Game, Adventure, Medieval, Sci-Fi, Interactive Fiction" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        
        {/* Open Graph / Facebook */}
        <meta property="og:type" content="website" />
        <meta property="og:url" content="https://chooseyourownadventure.vercel.app/" />
        <meta property="og:title" content="Choose Your Own AIdventure - AI RPG Game" />
        <meta property="og:description" content="An old-school style of RPG created using AI. Get a new Adventure every time!" />
        <meta property="og:image" content="https://chooseyourownadventure.vercel.app/og-image.png" />

        {/* Twitter */}
        <meta property="twitter:card" content="summary_large_image" />
        <meta property="twitter:url" content="https://chooseyourownadventure.vercel.app/" />
        <meta property="twitter:title" content="Choose Your Own AIdventure - AI RPG Game" />
        <meta property="twitter:description" content="An old-school style of RPG created using AI. Get a new Adventure every time!" />
        <meta property="twitter:image" content="https://chooseyourownadventure.vercel.app/og-image.png" />
      </Head>

      <Header/>

      <main id="nescss">
      <div className="container">
        <section className="showcase">
            <section className="nes-container with-title is-centered">
                <section className="adventures item">
                <Link
                  className="nes-btn is-primary"
                  href="/medieval"
                >
                  <h3>Medieval Adventure →</h3>
                </Link>
                <Link
                  className="nes-btn is-warning"
                  href="/scifi"
                >
                  <h3>Sci-Fi Adventure →</h3>
                </Link>
              </section>
            </section>
        </section>
      </div>
      </main>

    </>
  );
};

export default HomePage;


